
---

- hosts: all
  become: true
  pre_tasks:
   
  - name: install updates (CentOS)
    tags: always
    yum: 
     update_only: yes
     update_cache: yes
    when: ansible_distribution == "Centos"
  
  - name: install updates (Ubuntu)
    tags: always
    apt:
     upgrade: dist
     update_cache: yes
    when: ansible_distribution == "Ubuntu"


- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php for Ubuntu servers
    tags: apache,apache2,ubuntu
    apt: 
     name: 
       - apache2
       - libapache2-mod-php
     state: latest
     update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php for CentOS servers
    tags: apache,centos,httpd
    dnf:
     name:
       - httpd
       - php
     state: latest
    when: ansible_distribution == "CentOS"

  - name: start httpd (CentOS)
    tags: apache,centos,httpd
    service: 
      name: httpd
      state: started
    when: ansible_distribution == "CentOS"

- hosts: file_servers
  become: true
  tasks: 

  - name: instasll samba package
    tags: samba
    package:
      name: samba
      state: latest

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (CentOS)
    yum:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "CentOS"

  - name: "Mariadb- Restarting/Enabling"
    service:
      name: mariadb
      state: restarted
      enabled: true

  - name: install mariadb package (Ubuntu)
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"
 
